services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  hsshashank11/dsci522:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64