name: 522_milestone_env
channels:
  - conda-forge
dependencies:
  - python=3.11.4
  - ipykernel==6.29.5
  - numpy==2.1.3
  - pandas==2.2.3
  - pyjanitor==0.29.2
  - ucimlrepo==0.0.7
  - altair-all==5.4.1
  - altair==5.4.1
  - altair_tiles==0.3.0
  - vegafusion-python-embed==1.6.9
  - vegafusion==1.6.9
  - conda-lock==2.5.7
  - mamba
<<<<<<< HEAD
  - matplotlib==3.9.3
=======
  - pandera=0.21.0
>>>>>>> 74afaaea9bd27bd22b47c9000ff0453e2e2f7968
